(ns ecological.gbstudio.assets
  ;; (:require-macros [cljs.core.async.macros :refer [go]])
  ;; (:require [cljs-http.client :as http]
  ;;           [cljs.core.async :refer [<!]])
  ;(:require [datascript.core :as d])
  )


(defn asset-manifest []
[{:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\autogen_logo.png",
  :file "autogen_logo.png",
  :success true,
  :length 26753}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\BlackBackground.jpg",
  :file "BlackBackground.jpg",
  :success true,
  :length 1298}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\cave.png",
  :file "cave.png",
  :success true,
  :length 2352}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_01.png",
  :file "corridors_01.png",
  :success true,
  :length 3732}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_02.png",
  :file "corridors_02.png",
  :success true,
  :length 5130}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_03.png",
  :file "corridors_03.png",
  :success true,
  :length 5245}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_04.png",
  :file "corridors_04.png",
  :success true,
  :length 3734}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_05.png",
  :file "corridors_05.png",
  :success true,
  :length 6494}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\corridors_06.png",
  :file "corridors_06.png",
  :success true,
  :length 6131}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\c_test_1.png",
  :file "c_test_1.png",
  :success true,
  :length 3589}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\c_test_2.png",
  :file "c_test_2.png",
  :success true,
  :length 3598}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\c_test_3.png",
  :file "c_test_3.png",
  :success true,
  :length 3605}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01a.png",
  :file "Forest_01a.png",
  :success true,
  :length 2496}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01b.png",
  :file "Forest_01b.png",
  :success true,
  :length 1647}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01c.png",
  :file "Forest_01c.png",
  :success true,
  :length 1406}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01d.png",
  :file "Forest_01d.png",
  :success true,
  :length 1650}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01e.png",
  :file "Forest_01e.png",
  :success true,
  :length 3435}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2a.png",
  :file "Forest_01_2a.png",
  :success true,
  :length 3104}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2b.png",
  :file "Forest_01_2b.png",
  :success true,
  :length 2319}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2c.png",
  :file "Forest_01_2c.png",
  :success true,
  :length 3167}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2d.png",
  :file "Forest_01_2d.png",
  :success true,
  :length 2181}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2e.png",
  :file "Forest_01_2e.png",
  :success true,
  :length 2361}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2f.png",
  :file "Forest_01_2f.png",
  :success true,
  :length 2427}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2g.png",
  :file "Forest_01_2g.png",
  :success true,
  :length 1901}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2h.png",
  :file "Forest_01_2h.png",
  :success true,
  :length 2510}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2i.png",
  :file "Forest_01_2i.png",
  :success true,
  :length 2716}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2j.png",
  :file "Forest_01_2j.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2k.png",
  :file "Forest_01_2k.png",
  :success true,
  :length 3468}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2l.png",
  :file "Forest_01_2l.png",
  :success true,
  :length 2818}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2m.png",
  :file "Forest_01_2m.png",
  :success true,
  :length 2576}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2n.png",
  :file "Forest_01_2n.png",
  :success true,
  :length 2716}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Forest_01_2o.png",
  :file "Forest_01_2o.png",
  :success true,
  :length 2590}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_02.png",
  :file "halls_02.png",
  :success true,
  :length 1586}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_03.png",
  :file "halls_03.png",
  :success true,
  :length 1314}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_04.png",
  :file "halls_04.png",
  :success true,
  :length 1250}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_06.png",
  :file "halls_06.png",
  :success true,
  :length 1166}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_07.png",
  :file "halls_07.png",
  :success true,
  :length 990}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\halls_08.png",
  :file "halls_08.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\house.png",
  :file "house.png",
  :success true,
  :length 1896}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_01a.png",
  :file "link_01a.png",
  :success true,
  :length 1817}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_01b.png",
  :file "link_01b.png",
  :success true,
  :length 1086}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_01c.png",
  :file "link_01c.png",
  :success true,
  :length 1074}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_01d.png",
  :file "link_01d.png",
  :success true,
  :length 967}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_01e.png",
  :file "link_01e.png",
  :success true,
  :length 1921}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05a.png",
  :file "link_05a.png",
  :success true,
  :length 2116}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05b.png",
  :file "link_05b.png",
  :success true,
  :length 1298}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05c.png",
  :file "link_05c.png",
  :success true,
  :length 1279}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05d.png",
  :file "link_05d.png",
  :success true,
  :length 1170}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05e.png",
  :file "link_05e.png",
  :success true,
  :length 2313}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\link_05f.png",
  :file "link_05f.png",
  :success true,
  :length 3360}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\logo.png",
  :file "logo.png",
  :success true,
  :length 2204}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\menu.png",
  :file "menu.png",
  :success true,
  :length 2672}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\nothing.png",
  :file "nothing.png",
  :success true,
  :length 471}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\Old Halls by AFI.png",
  :file "Old Halls by AFI.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\outside.png",
  :file "outside.png",
  :success true,
  :length 6438}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\placeholder.png",
  :file "placeholder.png",
  :success true,
  :length 2002}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room1.png",
  :file "room1.png",
  :success true,
  :length 558}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room10.png",
  :file "room10.png",
  :success true,
  :length 594}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room11.png",
  :file "room11.png",
  :success true,
  :length 609}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room2.png",
  :file "room2.png",
  :success true,
  :length 588}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room3.png",
  :file "room3.png",
  :success true,
  :length 582}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room4.png",
  :file "room4.png",
  :success true,
  :length 634}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room5.png",
  :file "room5.png",
  :success true,
  :length 597}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room6.png",
  :file "room6.png",
  :success true,
  :length 555}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room7.png",
  :file "room7.png",
  :success true,
  :length 559}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room8.png",
  :file "room8.png",
  :success true,
  :length 570}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\room9.png",
  :file "room9.png",
  :success true,
  :length 613}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\savetheworld_01.png",
  :file "savetheworld_01.png",
  :success true,
  :length 4074}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\save_the_world_02.png",
  :file "save_the_world_02.png",
  :success true,
  :length 3521}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\save_the_world_03.png",
  :file "save_the_world_03.png",
  :success true,
  :length 3030}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\save_the_world_04.png",
  :file "save_the_world_04.png",
  :success true,
  :length 2172}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer11.png",
  :file "sewer11.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_01.png",
  :file "sewer_01.png",
  :success true,
  :length 7342}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_02.png",
  :file "sewer_02.png",
  :success true,
  :length 5222}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_03.png",
  :file "sewer_03.png",
  :success true,
  :length 7187}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_04.png",
  :file "sewer_04.png",
  :success true,
  :length 3375}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_05.png",
  :file "sewer_05.png",
  :success true,
  :length 3752}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_06.png",
  :file "sewer_06.png",
  :success true,
  :length 4737}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_07.png",
  :file "sewer_07.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_08.png",
  :file "sewer_08.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_09.png",
  :file "sewer_09.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_10.png",
  :file "sewer_10.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\sewer_12.png",
  :file "sewer_12.png",
  :success true,
  :length 0}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\stars.png",
  :file "stars.png",
  :success true,
  :length 2458}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\titlescreen.png",
  :file "titlescreen.png",
  :success true,
  :length 2368}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\underground.png",
  :file "underground.png",
  :success true,
  :length 3947}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\victory.png",
  :file "victory.png",
  :success true,
  :length 9174}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\victory.psd",
  :file "victory.psd",
  :success true,
  :length 218258}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\victory_old.png",
  :file "victory_old.png",
  :success true,
  :length 9697}
 {:category "backgrounds",
  :path ".\\data\\assets\\backgrounds\\youwin.png",
  :file "youwin.png",
  :success true,
  :length 6964}
 {:category "ban_list.json",
  :path ".\\data\\assets\\ban_list.json",
  :file "ban_list.json",
  :success true,
  :length 55}
 {:category "dialog.json",
  :path ".\\data\\assets\\dialog.json",
  :file "dialog.json",
  :success true,
  :length 4571}
 {:category "music",
  :path ".\\data\\assets\\music\\template.mod",
  :file "template.mod",
  :success true,
  :length 52234}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\actor.png",
  :file "actor.png",
  :success true,
  :length 5780}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\actor_animated.png",
  :file "actor_animated.png",
  :success true,
  :length 2076}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\bubbles1.png",
  :file "bubbles1.png",
  :success true,
  :length 2958}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\bubbles2.png",
  :file "bubbles2.png",
  :success true,
  :length 3034}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\cat.png",
  :file "cat.png",
  :success true,
  :length 5641}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\checkbox.png",
  :file "checkbox.png",
  :success true,
  :length 1751}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\closed_sewer_door.png",
  :file "closed_sewer_door.png",
  :success true,
  :length 3034}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\connector.png",
  :file "connector.png",
  :success true,
  :length 3594}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\dog.png",
  :file "dog.png",
  :success true,
  :length 1732}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\duck.png",
  :file "duck.png",
  :success true,
  :length 2092}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\duck_static.png",
  :file "duck_static.png",
  :success true,
  :length 3632}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\fire.png",
  :file "fire.png",
  :success true,
  :length 1847}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\GreenBlock.png",
  :file "GreenBlock.png",
  :success true,
  :length 763}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\hatch.png",
  :file "hatch.png",
  :success true,
  :length 2855}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\ice.png",
  :file "ice.png",
  :success true,
  :length 1710}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\invisible.png",
  :file "invisible.png",
  :success true,
  :length 2809}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\key_00.png",
  :file "key_00.png",
  :success true,
  :length 2915}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\ladder.png",
  :file "ladder.png",
  :success true,
  :length 2864}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin.png",
  :file "macguffin.png",
  :success true,
  :length 3011}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffins.psd",
  :file "macguffins.psd",
  :success true,
  :length 33594}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_bell.png",
  :file "macguffin_bell.png",
  :success true,
  :length 2928}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_book.png",
  :file "macguffin_book.png",
  :success true,
  :length 2956}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_candle.png",
  :file "macguffin_candle.png",
  :success true,
  :length 2992}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_crystal.png",
  :file "macguffin_crystal.png",
  :success true,
  :length 2948}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_egg.png",
  :file "macguffin_egg.png",
  :success true,
  :length 2960}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_harp.png",
  :file "macguffin_harp.png",
  :success true,
  :length 2963}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_heart.png",
  :file "macguffin_heart.png",
  :success true,
  :length 2937}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\macguffin_sword.png",
  :file "macguffin_sword.png",
  :success true,
  :length 2890}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\MazeBlock.png",
  :file "MazeBlock.png",
  :success true,
  :length 2920}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc001.png",
  :file "npc001.png",
  :success true,
  :length 1807}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc001_walk.png",
  :file "npc001_walk.png",
  :success true,
  :length 3225}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc002.png",
  :file "npc002.png",
  :success true,
  :length 1843}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc002_static.png",
  :file "npc002_static.png",
  :success true,
  :length 3653}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc003.png",
  :file "npc003.png",
  :success true,
  :length 1991}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\npc003_static.png",
  :file "npc003_static.png",
  :success true,
  :length 3668}
 {:category "sprites",
  :path
  ".\\data\\assets\\sprites\\overlay_fade_dither_one.png",
  :file "overlay_fade_dither_one.png",
  :success true,
  :length 2826}
 {:category "sprites",
  :path
  ".\\data\\assets\\sprites\\overlay_fade_dither_three.png",
  :file "overlay_fade_dither_three.png",
  :success true,
  :length 2839}
 {:category "sprites",
  :path
  ".\\data\\assets\\sprites\\overlay_fade_dither_two.png",
  :file "overlay_fade_dither_two.png",
  :success true,
  :length 2824}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\overlay_fade_straight.png",
  :file "overlay_fade_straight.png",
  :success true,
  :length 2818}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\player.png",
  :file "player.png",
  :success true,
  :length 1942}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\radio.png",
  :file "radio.png",
  :success true,
  :length 1715}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\rock.png",
  :file "rock.png",
  :success true,
  :length 1726}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\sage.png",
  :file "sage.png",
  :success true,
  :length 1737}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\savepoint.png",
  :file "savepoint.png",
  :success true,
  :length 1029}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\shovel.png",
  :file "shovel.png",
  :success true,
  :length 2977}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\signpost.png",
  :file "signpost.png",
  :success true,
  :length 5628}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\stairsdown.png",
  :file "stairsdown.png",
  :success true,
  :length 2859}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\static.png",
  :file "static.png",
  :success true,
  :length 5757}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\torch.png",
  :file "torch.png",
  :success true,
  :length 1739}
 {:category "sprites",
  :path ".\\data\\assets\\sprites\\tower.png",
  :file "tower.png",
  :success true,
  :length 3640}
 {:category "title.json",
  :path ".\\data\\assets\\title.json",
  :file "title.json",
  :success true,
  :length 6746}
 {:category "ui",
  :path ".\\data\\assets\\ui\\ascii.png",
  :file "ascii.png",
  :success true,
  :length 3508}
 {:category "ui",
  :path ".\\data\\assets\\ui\\cursor.png",
  :file "cursor.png",
  :success true,
  :length 1876}
 {:category "ui",
  :path ".\\data\\assets\\ui\\emotes.png",
  :file "emotes.png",
  :success true,
  :length 1639}
 {:category "ui",
  :path ".\\data\\assets\\ui\\frame.png",
  :file "frame.png",
  :success true,
  :length 5160}
 {:category "ui",
  :path ".\\data\\assets\\ui\\original\\ascii.png",
  :file "ascii.png",
  :success true,
  :length 3508}
 {:category "ui",
  :path ".\\data\\assets\\ui\\original\\cursor.png",
  :file "cursor.png",
  :success true,
  :length 1876}
 {:category "ui",
  :path ".\\data\\assets\\ui\\original\\emotes.png",
  :file "emotes.png",
  :success true,
  :length 1639}
 {:category "ui",
  :path ".\\data\\assets\\ui\\original\\frame.png",
  :file "frame.png",
  :success true,
  :length 5160}]

  )
